"""Unit tests for mapping COBOL names to GnuCOBOL-generated C symbols.

The header text below is taken verbatim from a real `cobc 3.2.0`
`-g -debug` compilation's generated `<name>.c.l.h` file, not a
hand-guessed format.
"""

from __future__ import annotations

from opencobol2.debugger.gnucobol_symbols import (
    parse_generated_symbol_map,
)


_REAL_LOCAL_HEADER = """\
/* Generated by           cobc 3.2.0 */
/* Generated from         demo.cbl */

/* Program local variables for 'DEMO' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_17[4] __attribute__((aligned));	/* WS-A */
static cob_u8_t	b_18[4] __attribute__((aligned));	/* WS-B */
static cob_u8_t	b_19[4] __attribute__((aligned));	/* WS-SUM */

/* End of local data storage */


/* Fields (local) */
static cob_field f_17	= {4, b_17, &a_1};	/* WS-A */
static cob_field f_18	= {4, b_18, &a_1};	/* WS-B */
static cob_field f_19	= {4, b_19, &a_1};	/* WS-SUM */

/* End of fields */
"""


def test_parse_generated_symbol_map_finds_every_data_item() -> None:
    symbols = parse_generated_symbol_map(
        _REAL_LOCAL_HEADER,
    )

    assert set(
        symbols,
    ) == {
        "WS-A",
        "WS-B",
        "WS-SUM",
    }


def test_parse_generated_symbol_map_captures_buffer_and_length() -> None:
    symbols = parse_generated_symbol_map(
        _REAL_LOCAL_HEADER,
    )

    ws_a = symbols["WS-A"]
    assert ws_a.cobol_name == "WS-A"
    assert ws_a.buffer_variable == "b_17"
    assert ws_a.byte_length == 4


def test_parse_generated_symbol_map_skips_non_buffer_declarations() -> None:
    symbols = parse_generated_symbol_map(
        _REAL_LOCAL_HEADER,
    )

    # RETURN-CODE is declared as a plain `int`, not `cob_u8_t name[N]`,
    # so it isn't a raw byte buffer this decoder can meaningfully read.
    assert "RETURN-CODE" not in symbols


def test_parse_generated_symbol_map_merges_multiple_headers() -> None:
    other_header = (
        "static cob_u8_t\tb_30[10] "
        "__attribute__((aligned));\t/* WS-GLOBAL */\n"
    )

    symbols = parse_generated_symbol_map(
        _REAL_LOCAL_HEADER,
        other_header,
    )

    assert "WS-A" in symbols
    assert "WS-GLOBAL" in symbols
    assert (
        symbols["WS-GLOBAL"].buffer_variable
        == "b_30"
    )


def test_parse_generated_symbol_map_later_header_overrides_earlier() -> None:
    first = (
        "static cob_u8_t\tb_1[4] "
        "__attribute__((aligned));\t/* WS-X */\n"
    )
    second = (
        "static cob_u8_t\tb_2[8] "
        "__attribute__((aligned));\t/* WS-X */\n"
    )

    symbols = parse_generated_symbol_map(
        first,
        second,
    )

    assert symbols["WS-X"].buffer_variable == "b_2"
    assert symbols["WS-X"].byte_length == 8


def test_parse_generated_symbol_map_of_empty_text_is_empty() -> None:
    assert (
        parse_generated_symbol_map(
            "",
        )
        == {}
    )


# Taken verbatim from a real `cobc 3.2.0` `-g -debug` compilation of a
# WORKING-STORAGE group record (`CUSTOMER-REC`) with two nested
# elementary items, plus a REDEFINES view of a separate top-level item.
_REAL_GROUP_HEADER = """\
static cob_u8_t\tb_17[8] __attribute__((aligned));\t/* CUSTOMER-REC */
static cob_u8_t\tb_22[3] __attribute__((aligned));\t/* WS-REDEF-BASE */

static cob_field f_18\t= {3, b_17, &a_1};\t/* CUST-AMOUNT */
static cob_field f_19\t= {5, b_17 + 3, &a_3};\t/* CUST-BALANCE */
static cob_field f_23\t= {3, b_22, &a_1};\t/* WS-REDEF-VIEW */
"""


def test_parse_generated_symbol_map_recovers_a_group_member_at_offset_zero() -> (
    None
):
    # Editor §DebuggerLogic-1: a group member at the start of its
    # group's buffer has no offset of its own, only the group's own
    # buffer variable directly.
    symbols = parse_generated_symbol_map(
        _REAL_GROUP_HEADER,
    )

    cust_amount = symbols["CUST-AMOUNT"]
    assert cust_amount.buffer_variable == "b_17"
    assert cust_amount.byte_length == 3


def test_parse_generated_symbol_map_recovers_a_group_member_at_a_nonzero_offset() -> (
    None
):
    # Editor §DebuggerLogic-1: a group member after the first one gets
    # a constant byte offset into the shared group buffer -- GDB's own
    # expression evaluator understands `buffer+N` directly, so no
    # separate offset field is needed on `GeneratedFieldSymbol`.
    symbols = parse_generated_symbol_map(
        _REAL_GROUP_HEADER,
    )

    cust_balance = symbols["CUST-BALANCE"]
    assert cust_balance.buffer_variable == "b_17+3"
    assert cust_balance.byte_length == 5


def test_parse_generated_symbol_map_recovers_a_redefines_view() -> None:
    # Editor §DebuggerLogic-3: a REDEFINES view gets the identical
    # `cob_field`-pointing-into-another-buffer shape as a group member,
    # here pointing at `WS-REDEF-BASE`'s own dedicated buffer.
    symbols = parse_generated_symbol_map(
        _REAL_GROUP_HEADER,
    )

    redefines_view = symbols["WS-REDEF-VIEW"]
    assert redefines_view.buffer_variable == "b_22"
    assert redefines_view.byte_length == 3


def test_parse_generated_symbol_map_does_not_confuse_group_and_members() -> (
    None
):
    symbols = parse_generated_symbol_map(
        _REAL_GROUP_HEADER,
    )

    assert set(
        symbols,
    ) == {
        "CUSTOMER-REC",
        "WS-REDEF-BASE",
        "CUST-AMOUNT",
        "CUST-BALANCE",
        "WS-REDEF-VIEW",
    }
